### ISSUE TITLE
split gcs out into a different project

### ISSUE THREAD

**Issue by lancecarlson** [surma/s3put#4]
It doesn't make any sense to me that gcs is also used in this project. Perhaps a separate gcsput project could be made. Would also simplify this project's implementation.

**Comment by lancecarlson** [comment]
How about removing the verbs in the API? Feel like since you require the full URL in the -b argument, it should just recognize gcs vs s3 from that?

**Comment by surma** [comment]
@lancecarlson Yeah. That’s a totally fair point and I was actually confused over this myself after rusing `s3put` a few weeks ago, lol. Mind opening another issue?
