### ISSUE TITLE
dots in bucket name ssl error

### ISSUE THREAD

**Issue by jschoch** [surma/s3put#5]
any chance you can fix this issue referenced here

https://github.com/boto/boto/issues/2836

**Comment by surma** [comment]
Hey @jschoch,

I am not affected by this bug, although you might have to use another mutation. I just tested with the following command:

```
$ s3put s3 -k <key> -s <secrey> -b https://s3-eu-west-1.amazonaws.com/f.surma.link put .
```

I’m closing this, but feel free to re-open if I am misunderstanding you.
