### ISSUE TITLE
Precompiled links broken

### ISSUE THREAD

**Issue by nwgat** [surma/s3put#6]
404 Not Found

Code: NoSuchBucket
Message: The specified bucket does not exist
BucketName: filedump.surmair.de
RequestId: 3244DC22B0A86945
HostId: WC2f48ZGsD/6rnTOh3nSicbsmFTdNigc6Y/zxcnEnNe7Sc0gAAbeQI+NchXG/gOfk/6FIQD+k8g=

**Comment by surma** [comment]
I am an idiot!

I removed that comment from the README and will from now on put binaries into the [release section](https://github.com/surma/s3put/releases) of the repo. Thanks for the issue, @nwgat!

**Comment by nwgat** [comment]
well i did figure out howto compile the go files on linux, so no worries :)

**Comment by nwgat** [comment]
FYI would have been useful if you also upped a win32 bin,  there are alot of companies that use 32-bit windows still, and alot of older costumer systems run it too

**Comment by surma** [comment]
Fix'd :wink:
