### ISSUE TITLE
Error While Running S3 put

### ISSUE THREAD

**Issue by amitsidhim** [surma/s3put#7]
Hello , 

I am having Errors while running the script 

./s3put.go
./s3put.go: line 1: package: command not found
./s3put.go: line 3: syntax error near unexpected token `newline'
./s3put.go: line 3: `import ('

Running on RHEL 6.6 2.6.32-573.el6.x86_64

Thanks,

**Comment by surma** [comment]
This is not a script. It’s a [go](https://golang.org) program. You need to compile it or download the binary from the [release section](https://github.com/surma/s3put/releases).

**Comment by amitsidhim** [comment]
Thanks , My BAD

**Comment by amitsidhim** [comment]
So you have any blog for support Actually I am trying to upload to a customized  S3 storage with different port number 

http://<hostname>:8143 and the command fails with endpoint "Invalid storage credentials: Unknown region endpoint" Is there a way to give a port number

**Comment by surma** [comment]
A blog for support? What do you mean? :D 

`s3put` uses the hardcoded endpoints of `launchpad.net/goamz/s3`, so custom S3-like setups are not support right now. Sorry.
