### ISSUE TITLE
Remove the gcs and s3 "commands" in favor of figuring out the service from the -b url

### ISSUE THREAD

**Issue by lancecarlson** [surma/s3put#8]
Referenced from here:

https://github.com/surma/s3put/issues/4#issuecomment-64272913

**Comment by lancecarlson** [comment]
@surma Let me know if that was a good enough description or if I botched it! haha

**Comment by surma** [comment]
:+1: Perfect! Thank you :)

**Comment by surma** [comment]
Fixed in v3.0.0 :) Binaries in the [release section](https://github.com/surma/s3put/releases)

**Comment by mbeacom** [comment]
Whoa, glad I checked this! haha  I was just about to push this fix.  Thank you, @surma !

**Comment by nwgat** [comment]
FYI release section has 3.0.0 and 3.0.1?

**Comment by surma** [comment]
3.0.1 was just a documentation fix. The fix got implemented with 3.0.0 and is obviously in all subsequent v3 releases.

**Comment by nwgat** [comment]
32-bit bin for windows mia , was there for older version

**Comment by surma** [comment]
Fix’d
